name: Build with Webpack and Publish to GitHub Pages

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Build with Webpack
      run: |
        yarn install --frozen-lockfile
        yarn build-prod

    - name: Upload generated files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
